name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.4

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          . $IDF_PATH/export.sh
          idf.py set-target esp32h2
          idf.py build
